name: Verify that tests pass on all platforms

on: [push]

jobs:
  lint_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          rm -rf 0/
          flake8 cyanure --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 cyanure --count --max-complexity=10 --max-line-length=110 --statistics

  build_wheels:
    needs: [lint_code]
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.8'
          
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.2.0a1

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  test_imports:
    needs: [build_wheels]
    name: Smoke test for c++ depenencies on raw ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.7']

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: artifact
        path: dist

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Try to import cyanure
      run: python -m pip install --find-links dist cyanure &&  python -c "import cyanure;"

  run_tests:
    needs: [build_wheels]
    name: Run the tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.7']

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: artifact
        path: dist
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Install cyanure
      run: python -m pip install dist/cyanure*.whl
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
          
    - name: Switch to Current Branch
      run: git checkout ${{ env.BRANCH }}

    - name: Run tests without the lib
      uses: knicknic/os-specific-run@v1.0.3
      with:
        macos: rm -rf cyanure && rm -rf cyanure_lib && python -m pip install pytest && python -m pip install pandas && python -m pytest test/
        linux: rm -rf cyanure && rm -rf cyanure_lib && python -m pip install pytest && python -m pip install pandas && python -m pytest test/ 
        windows: Remove-Item -Force -Recurse cyanure && Remove-Item -Force -Recurse cyanure_lib && python -m pip install pytest && python -m pip install pandas && python -m pytest test/
