name: Sphinx build

on: 
  push: 
    branches: 
      - master
      - mlflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Update pip and install openblas
      run: |
        python -m pip install --upgrade pip && sudo apt-get upgrade && sudo apt-get install -y libopenblas-dev
    - name: Install the package your documenting together with its dependencies.
      run: |
        pip install .
    - name: Install the building dependencies.
    # With higher version of docutils bullet lists does not work
      run: |
        pip install sphinx ipywidgets beautifulsoup4 sphinx-rtd-theme numpydoc furo autodocsumm docutils==0.16.0
    - name: Build the sphinx documentation and posts warnings as github comments.
      run: cd docs/sphinx/source && sphinx-build -b html . _build && cd _build && mkdir dash
    - name: Build the sphinx documentation and posts warnings as github comments.
      run: cd docs/dash/ && make html && cd ../..
    - name: Build the sphinx documentation and posts warnings as github comments.
      run: cp -r docs/dash/127.0.0.1:8050/. docs/sphinx/source/_build/dash
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: html-docs
        path: docs/sphinx/source/_build/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/sphinx/source/_build/