name: Sphinx build

on: 
  push: 
    branches: 
      - master
      - mlflow
      - debug-cluster

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python environment
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Update pip and install openblas
      run: |
        python -m pip install --upgrade pip && sudo apt-mark hold grub-efi-amd64-signed && sudo apt-get update --fix-missing && sudo apt-get upgrade && sudo apt-get install -y libopenblas-dev
    - name: Install the package your documenting together with its dependencies.
      run: |
        pip install .
    - name: Install the building dependencies.
    # With higher version of docutils bullet lists does not work
      run: |
        pip install sphinx ipywidgets beautifulsoup4 sphinx-rtd-theme numpydoc furo autodocsumm docutils==0.16.0 pandas plotly dash==2.5.0
    - name: Build the sphinx documentation and posts warnings as github comments.
      run: cd docs/sphinx/source && sphinx-build -b html . _build && cd _build && mkdir dash
    - name: Build the dash html.
      run: git lfs pull && cd docs/dash/ && make html
    - name: Copy the dash website to sphinx folder.
      run: cp -r docs/dash/127.0.0.1:8050/. docs/sphinx/source/_build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/sphinx/source/_build/